ingress:
  enabled: false
api:
  image:
    tag: '81'
  annotations: |
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/transparent-proxy": "false"
  kafka:
    topics:
      blocks: blocks-raw
      transactions: transactions-raw
      logs: logs-raw
worker:
  image:
    tag: '81'
  kafka:
    topics:
      blocks: blocks-raw
      transactions: transactions-raw
      logs: logs-raw
db:
  sslMode: require
