name: release

# 1. Run unit and integration tests
# 2. Push containers to AWS ECR and dockerhub tagged with release
# 3. Recommit an update to the chart's deployments with the updated build number in the `deployment` branch

on:
  release:
    types: [created]
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create last_synced_block.txt
        run: mkdir ./volumes && mkdir ./volumes/etl && echo "34000000" >> ./volumes/etl/last_synced_block.txt && chmod 777 ./volumes/etl/last_synced_block.txt

      - name: Bring up DBs
        run: docker-compose -f docker-compose.db.yml up -d && sleep 30

      - name: Check DBs
        run: make ps

      - name: Run unit tests
        run: cd src && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/coverage.out
          flags: unit
          fail_ci_if_error: true

      - name: Bring up stack
        run: make up && sleep 30

      - name: Check stack
        run: make ps

      - name: Check ETL logs
        run: docker-compose -f docker-compose.yml -f docker-compose.db.yml logs --tail=100 etl

      - name: Check worker logs
        run: docker-compose -f docker-compose.yml -f docker-compose.db.yml logs --tail=100 blocks-worker

      - name: Check api logs
        run: docker-compose -f docker-compose.yml -f docker-compose.db.yml logs --tail=100 blocks-api

      - name: Run integration tests
        run: cd tests && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/coverage.out
          flags: integration
          fail_ci_if_error: true

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_WORKER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_WORKER }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr-worker
        uses: aws-actions/amazon-ecr-login@v1

      - name: Worker - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-worker.outputs.registry }}
          ECR_REPOSITORY: icon-blocks-worker
          IMAGE_TAG: ${{ steps.source.outputs.TAG }}
        run: |
          docker build --target prod --build-arg SERVICE_NAME=worker -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_API }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_API }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr-api
        uses: aws-actions/amazon-ecr-login@v1

      - name: API - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-api.outputs.registry }}
          ECR_REPOSITORY: icon-blocks-api
          IMAGE_TAG: ${{ steps.source.outputs.TAG }}
        run: |
          docker build --target prod  --build-arg SERVICE_NAME=api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (API) - latest
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SERVICE_NAME=api
          file: ./Dockerfile
          target: prod
          push: true
          tags: geometrylabs/icon-blocks-api:latest

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SERVICE_NAME=api
          file: ./Dockerfile
          target: prod
          push: true
          tags: geometrylabs/icon-blocks-api:${{ steps.source.outputs.TAG }}

      - name: Build and push (WORKER) - latest
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SERVICE_NAME=api
          file: ./Dockerfile
          target: prod
          push: true
          tags: geometrylabs/icon-blocks-api:latest

      - name: Build and push (WORKER)
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SERVICE_NAME=api
          file: ./Dockerfile
          target: prod
          push: true
          tags: geometrylabs/icon-blocks-api:${{ steps.source.outputs.TAG }}

      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: geometry-labs/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Update prod-mainnet deployment values file (API) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/mainnet/blocks/values.yaml'
          propertyPath: 'api.image.tag'
          value: prod-${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod-mainnet deployment values file (builder) and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/mainnet/blocks/values.yaml'
          propertyPath: 'builder.image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod-mainnet deployment values file (WORKER) and re-commit
        id: yaml-update
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/mainnet/blocks/values.yaml'
          propertyPath: 'worker.image.tag'
          value: prod-${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          message: 'blocks prod deployment (mainnet) image versions to ${{ steps.source.outputs.TAG }}'
          token: ${{ secrets.ICON_CHARTS_PAT }}
          updateFile: true

      - name: Remove volumes
        run: sudo rm -rf volumes

      - name: Push tags
        run: |
          git stash
          git pull
          git tag -f blocks-prod-uswest2 ${{ steps.yaml-update.outputs.commit }}
          git tag -f blocks-prod-euwest2 ${{ steps.yaml-update.outputs.commit }}
          git push -f origin --tags
        working-directory: charts
